services:
  - type: web
    name: almoxarifado-pro
    env: node
    plan: free
    buildCommand: cd server && pnpm install
    startCommand: cd server && node index.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
